// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  logos: dynamic(() => import("./Logos")),
  slider: dynamic(() => import("./Slider")),
};
